### ISSUE TITLE
Images for social cards

### ISSUE THREAD

**Issue by darylshaw** [darylshaw/darylshaw.co.uk#26]
I can define a default image using front matter defaults.

Example:

```
defaults:
  - scope:
      path: ""
    values:
      image: /assets/uploads/default-card.png
```

The empty string for path means all files and is required when working with scope/values pairs.

I can then override this default on a per-page/post basis by setting an image in the front matter for that page/post. 

Alternatively I could roll my own meta tags. This would give me more control over title tags.

A sensible middleground might be to disable title output on pages like the homepage using:

```
{% seo title=false %}
```

This means I have more control over title tag separators on those pages. Then leave Jekyll SEO tag as is for pages where I don't want to customise.
