### ISSUE TITLE
Update permalinks for blog section

### ISSUE THREAD

**Issue by darylshaw** [darylshaw/darylshaw.co.uk#30]
Update defaults in `_config.yml` from:

```
defaults:
-
  scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
    permalink: "/blog/:title/"
    post_type: "Article"
```

to:

```
defaults:
-
  scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
    permalink: "/articles/:title/"
    post_type: "Article"
```

Set up 301 redirects for posts e.g. /blog/switching-micropub-endpoint-to-indiekit/ > /articles/switching-micropub-endpoint-to-indiekit/. Complete at same time as #21
